site_name: Linked Data Competency Index
pages:
    - About: 'index.md'
    - The Index: 'D2695955.md'
    - Structure of the Index: 'structure.md'
    - Style of the Index: 'style.md'
    - How to Contribute: 'process.md'
    - Editorial Board: 'board.md'
    - FAQ: 'faq.md'
theme: 'readthedocs'
repo_url: https://github.com/dcmi/ldci
repo_name: 'Github'
edit_uri: 'edit/master/docs/'
site_description: 'For crowdsourcing the maintenance and evolution of the LD4PE Linked Data Competency Index'
